# Generated by Django 5.2.4 on 2025-07-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
